[package]
name = "emu"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
lettre = "0.11.4"
serde = "1.0"
serde_derive = "1.0"
toml = "0.8"
dirs = "3.0"
tempfile = "3.10.0"
